### ISSUE TITLE
Can't add external styles to components

### ISSUE THREAD

**Issue by apust** [cft-group/elephas-angular#5]
When using components, I can't apply CSS styles without doing things you won't expect a library user to do.

Say I write this CSS in my module:

```CSS
.app .el-button {
  margin-left: 20px;
}
```

In this case, I have to disable encapsulation for the module, because `.el-button` class is used in an external component.

The other case is when I use `className` property like that:

```HTML
<el-button [className]="'custom-button'">Click Me</el-button>
```

```CSS
.custom-button {
   margin-left: 20px !important;
}
```

I have to add `!important` flag to styles. If I don't do that, they become overwritten by component's own reset. And I have to disable encapsulation as well.

We need to come up with a solution that allows for easier user styling.
